[platformio]
src_dir = src
default_envs = i2c, spi

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:i2c]
build_src_filter = +<speed_esp32_I2C/> -<*>

[env:spi]
build_src_filter = +<speed_esp32_SPI/> -<*>
